// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reservation.Persistence;

#nullable disable

namespace Reservation.Persistence.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    [Migration("20250920202812_AddIndexToReservationsTable")]
    partial class AddIndexToReservationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reservation.Persistence.Entities.FailedReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Raw_Request")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FailedReservations", (string)null);
                });

            modelBuilder.Entity("Reservation.Persistence.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Raw_Request")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Validation_Result")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Reservation_Id");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("Reservation.Persistence.Entities.SuccessfulReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Raw_Request")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SuccessfulReservations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
